<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>AiNewsBot_Backend</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4"/>
        <PackageReference Include="DotNetEnv" Version="3.1.1"/>
        <PackageReference Include="Hangfire.AspNetCore" Version="1.8.22"/>
        <PackageReference Include="Hangfire.Core" Version="1.8.22"/>
        <PackageReference Include="Hangfire.MemoryStorage" Version="1.8.1.2"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.10"/>
        <PackageReference Include="OpenRouter.NET" Version="0.5.0" />
    </ItemGroup>

</Project>
